---
- name: "Provision VM from template"
  hosts: localhost
  gather_facts: false
  connection: local

  collections:
    - name: xyz.vmware

  roles:
    - name: xyz.vmware.vm_provision
    #- name: xyz.awx.add_host