---
- name: "Build VMware Packer Templates"
  hosts: localhost
  gather_facts: true
  connection: local

  collections:
    - xyz.packer
    - xyz.vmware

  roles:
    - { role: xyz.packer.install, become: true }
    - xyz.vmware.vm_templates