---
- name: "Build VMware Packer Templates"
  hosts: localhost
  gather_facts: false
  connection: local

  collections:
    #- xyz.packer
    #- xyz.vmware
    - xyz.awx

  roles:
    #- xyz.packer.install
    #- xyz.vmware.vm_templates
    - xyz.awx.update_survey