xyz_awx_update_survey_vm_template_values_prompt:
  - question_name: 'VM Name'
    question_description: ''
    required: true
    type: 'text'
    variable: 'xyz_vmware_vm_name'
    min: '0'
    max: '15'
    default: ''
    choices: ''
  - question_name: 'Type'
    question_description: ''
    required: true
    type: 'multiplechoice'
    variable: 'xyz_vmware_vm_type'
    min: 'null'
    max: 'null'
    default: 'DEV'
    choices: 'DEV\nTST\nPRD'
  - question_name: 'CPU'
    question_description: ''
    required: true
    type: 'multiplechoice'
    variable: 'xyz_vmware_vm_num_cpus'
    min: 'null'
    max: 'null'
    default: '2'
    choices: '2\n4'
  - question_name: 'Memory (MB)'
    question_description: ''
    required: true
    type: 'multiplechoice'
    variable: 'xyz_vmware_vm_memory_mb'
    min: 'null'
    max: 'null'
    default: '4096'
    choices: '1024\n2048\n4096'
  - question_name: 'Template'
    question_description: ''
    required: true
    type: 'multiplechoice'
    variable: 'xyz_vmware_vm_template'
    min: 'null'
    max: 'null'
    default: '{{ xyz_awx_update_survey_vm_template_values_add }}'
    choices: '{{ jt_survey_spec_new_templates_choices | join("\n") }}'
  - question_name: 'Roles'
    question_description: ''
    required: true
    type: 'multiselect'
    variable: 'xyz_vmware_vm_provision_roles'
    min: 'null'
    max: 'null'
    default: 'common'
    choices: 'common'
  - question_name: 'VLAN'
    question_description: ''
    required: true
    type: 'multiplechoice'
    variable: 'xyz_vmware_vm_vlan'
    min: 'null'
    max: 'null'
    default: 'VLAN100 - INF'
    choices: 'VLAN100 - INF\nVLAN015 - NSX\nVLAN200 - DMZ'
  - question_name: 'Destroy'
    question_description: ''
    required: true
    type: 'multiplechoice'
    variable: 'xyz_vmware_vm_destroy'
    min: 'null'
    max: 'null'
    default: 'False'
    choices: 'False\nTrue'
