---
# - name: Windows
#   include_tasks: "play_windows.yml"
#   when: ""

- debug:
    msg: "{{ ansible_distribution }}"

- debug:
    msg: "{{ ansible_distribution_version }}"

- debug:
    msg: "{{ ansible_distribution_major_version  }}"